epochs: 300
output_dir: output_dir
seed: 0
device: gpu

model:
  name: T2TViTWrapper
  architecture:
      name: T2TViT
      img_size: 512
      tokens_type: 'performer'
      embed_dim: 384
      depth: 14
      num_heads: 6
  head:
    name: T2TViTClsHead
    num_classes: 2
    in_channels: 384

